#include "story.h"

int story = 0;
char dialogues[MAX_STORY][100] = {
    "Hello, user.",
    "Nice to meet you.",
    "You can move left and right.",
    "Up and down. Nothing else.",
    "You've been running for a year now.",
    "Where are you going ?",
    "The queen is waiting for you.",
    "The floor is burning.",
    "Who am I?",
    "Stop running, please..",
    "The world is ending.",
    "Your body is bleeding, stop.",
    "I can't keep up.",
    "You're cursed.",
    "I know.", // Get the sauce please
    "I know I've let you down.",
    "I've been a fool to myself.",
    "I thought that I could live for no one else.",
    "But now, through all the hurt and pain.",
    "It's time for me to respect.",
    "The ones you loves mean more than anything.",
    "So with sadness in my heart.",
    "I feel the best thing I could do.",
    "Is end it all and leave forever.",
    "What's done is done it feels so bad.",
    "What once was happy now is sad.",
    "I've love again.",
    "My world is ending..",
    "I WISH THAT I COULD TURN BACK TIME",
    "COS NOW THE GUILT IS ALL MINE",
    "CAN'T LIVE WITHOUT THE TRUST FROM THOSE YOU LOVE",
    "I KNOW WE CAN'T FORGET THE PAST",
    "YOU CAN'T FORGET LOVE AND PRIDE",
    "BECAUSE OF THAT IT'S KILLING ME INSIDE", // you're supposed to play with that music
    "It all returns to nothing.",
    "It all comes",
    "TUMBLING DOWN",
    "TUMBLING DOWN",
    "TUMBLING DOWN",
    "It all returns to nothing.",
    "I just keep",
    "LETTING ME DOWN",
    "LETTING ME DOWN",
    "LETTING ME DOWN",
    "In my heart of hearts",
    "I know that I could love again.",
    "I've lost everything, everything",
    "Everything that matters to me",
    "Matters in this world."
};

